"""empty message

Revision ID: 0f2ed5e61ded
Revises: 262cc1d23631
Create Date: 2021-03-31 02:12:34.579225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2ed5e61ded'
down_revision = '262cc1d23631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telephone', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'user', ['telephone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'telephone')
    # ### end Alembic commands ###
