"""empty message

Revision ID: 7e0ff0d5b1d6
Revises: 3c128702ced1
Create Date: 2021-04-02 08:44:17.827974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e0ff0d5b1d6'
down_revision = '3c128702ced1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('event', sa.Column('start_date', sa.Date(), nullable=False))
    op.drop_index('category', table_name='event')
    op.drop_index('description', table_name='event')
    op.drop_index('held_date', table_name='event')
    op.drop_column('event', 'held_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('held_date', mysql.DATETIME(), nullable=False))
    op.create_index('held_date', 'event', ['held_date'], unique=True)
    op.create_index('description', 'event', ['description'], unique=True)
    op.create_index('category', 'event', ['category'], unique=True)
    op.drop_column('event', 'start_date')
    op.drop_column('event', 'end_date')
    # ### end Alembic commands ###
