"""empty message

Revision ID: 82181db5b514
Revises: 0f2ed5e61ded
Create Date: 2021-04-02 06:18:46.478334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82181db5b514'
down_revision = '0f2ed5e61ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.String(length=2), nullable=False))
    op.add_column('user', sa.Column('province', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'province')
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
