"""empty message

Revision ID: 97129903d82d
Revises: 7e0ff0d5b1d6
Create Date: 2021-04-02 10:41:57.297394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97129903d82d'
down_revision = '7e0ff0d5b1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'event', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'user_id')
    # ### end Alembic commands ###
