"""empty message

Revision ID: fef27aa34f95
Revises: 34b3e821cf91
Create Date: 2021-04-26 16:46:51.863431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef27aa34f95'
down_revision = '34b3e821cf91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'verification', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification', type_='foreignkey')
    op.drop_column('verification', 'user_id')
    # ### end Alembic commands ###
